#!/usr/bin/env python3
"""Generate a reproducible workflow comparison from exact run reports."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPEC = (
    PROJECT_ROOT
    / "benchmark"
    / "comparisons"
    / "advanced-v1-development.spec.json"
)
DEFAULT_JSON = (
    PROJECT_ROOT / "benchmark" / "comparisons" / "advanced-v1-development.json"
)
DEFAULT_MARKDOWN = (
    PROJECT_ROOT / "benchmark" / "comparisons" / "advanced-v1-development.md"
)
TOKEN_FIELDS = (
    "input_tokens",
    "cached_input_tokens",
    "output_tokens",
    "reasoning_output_tokens",
)


def load_object(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"expected JSON object: {path}")
    return value


def source_row(workflow: str, run_id: str) -> dict[str, Any]:
    relative_report = Path("benchmark") / "results" / run_id / "report.json"
    report_path = PROJECT_ROOT / relative_report
    raw_report = report_path.read_bytes()
    report = json.loads(raw_report)
    if report.get("run_id") != run_id:
        raise ValueError(f"run ID mismatch in {relative_report}")
    report_workflow = report.get("workflow")
    if report_workflow is not None and report_workflow != workflow:
        raise ValueError(
            f"workflow mismatch in {relative_report}: {report_workflow!r}"
        )
    metrics = report["metrics"]
    usage = report.get("usage") or {}
    return {
        "workflow": workflow,
        "case_id": report["case_id"],
        "run_id": run_id,
        "verified_repair": bool(metrics["verified_repair"]),
        "evidence_backed_repair": bool(metrics["evidence_backed_repair"]),
        "runtime_seconds": report["agent"]["runtime_seconds"],
        "input_tokens": usage.get("input_tokens"),
        "cached_input_tokens": usage.get("cached_input_tokens"),
        "output_tokens": usage.get("output_tokens"),
        "reasoning_output_tokens": usage.get("reasoning_output_tokens"),
        "retry_count": usage.get("retry_count", 0) or 0,
        "changed_files": report["patch_files"],
        "source_report": relative_report.as_posix(),
        "source_report_sha256": hashlib.sha256(raw_report).hexdigest(),
    }


def aggregate(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    aggregates: list[dict[str, Any]] = []
    workflows = list(dict.fromkeys(row["workflow"] for row in rows))
    for workflow in workflows:
        selected = [row for row in rows if row["workflow"] == workflow]
        token_totals: dict[str, int | None] = {}
        for field in TOKEN_FIELDS:
            values = [row[field] for row in selected]
            token_totals[field] = (
                sum(values) if all(isinstance(value, int) for value in values) else None
            )
        aggregates.append(
            {
                "workflow": workflow,
                "cases": len(selected),
                "verified_repairs": sum(row["verified_repair"] for row in selected),
                "evidence_backed_repairs": sum(
                    row["evidence_backed_repair"] for row in selected
                ),
                "runtime_seconds": round(
                    sum(row["runtime_seconds"] for row in selected), 6
                ),
                **token_totals,
                "retry_count": sum(row["retry_count"] for row in selected),
                "changed_files": sorted(
                    {path for row in selected for path in row["changed_files"]}
                ),
            }
        )
    return aggregates


def build_artifact(spec_path: Path) -> dict[str, Any]:
    spec = load_object(spec_path)
    rows = [
        source_row(workflow, run_id)
        for workflow, run_ids in spec["workflows"].items()
        for run_id in run_ids
    ]
    case_sets = {
        workflow: {row["case_id"] for row in rows if row["workflow"] == workflow}
        for workflow in spec["workflows"]
    }
    if len({frozenset(cases) for cases in case_sets.values()}) != 1:
        raise ValueError(f"workflow case sets differ: {case_sets}")
    return {
        "schema_version": "1.0",
        "comparison_id": spec["comparison_id"],
        "selection_policy": spec["selection_policy"],
        "source_spec": spec_path.relative_to(PROJECT_ROOT).as_posix(),
        "rows": rows,
        "aggregate": aggregate(rows),
    }


def markdown(artifact: dict[str, Any]) -> str:
    lines = [
        "# Advanced v1 development comparison",
        "",
        "This file is generated by `scripts/generate_comparison.py` from the exact run reports listed below.",
        "",
        f"Selection policy: {artifact['selection_policy']}",
        "",
        "## Selected runs",
        "",
        "| Workflow | Case | Run ID | Verified | Evidence-backed |",
        "|---|---|---|---:|---:|",
    ]
    for row in artifact["rows"]:
        lines.append(
            f"| {row['workflow']} | {row['case_id']} | `{row['run_id']}` | "
            f"{'yes' if row['verified_repair'] else 'no'} | "
            f"{'yes' if row['evidence_backed_repair'] else 'no'} |"
        )
    lines.extend(
        [
            "",
            "## Aggregate",
            "",
            "| Workflow | Verified | Evidence-backed | Runtime (s) | Input | Cached input | Output | Reasoning | Retries |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for row in artifact["aggregate"]:
        lines.append(
            f"| {row['workflow']} | {row['verified_repairs']}/{row['cases']} | "
            f"{row['evidence_backed_repairs']}/{row['cases']} | "
            f"{row['runtime_seconds']:.3f} | {row['input_tokens']} | "
            f"{row['cached_input_tokens']} | {row['output_tokens']} | "
            f"{row['reasoning_output_tokens']} | {row['retry_count']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    parser.add_argument("--output", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MARKDOWN)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    artifact = build_artifact(args.spec.resolve())
    json_text = json.dumps(artifact, indent=2, sort_keys=True) + "\n"
    markdown_text = markdown(json.loads(json_text))
    if args.check:
        stale = []
        for path, expected in (
            (args.output, json_text),
            (args.markdown, markdown_text),
        ):
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(str(path))
        if stale:
            print(f"comparison artifacts are stale: {', '.join(stale)}", file=sys.stderr)
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json_text, encoding="utf-8")
    args.markdown.write_text(markdown_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
